apiVersion: v1
kind: PersistentVolume
metadata:
  name: yvakil-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 0.01Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/"