apiVersion: v1
kind: PersistentVolume
metadata:
  name: yvakil-pv
  labels:
    type: local
spec:
  storageClassName: slow
  capacity:
    storage: 0.001Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/public"